enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomIcon=youtube -OcustomName=YouTube_RVX -e 'Change header' -Ocustom=custom_branding_icon -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Custom header for YouTube' -e 'MaterialYou' -e 'Return YouTube Username'"

[Music-Extended]
enabled = true
app-name = "YouTube-Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomIcon=youtube_music -OcustomName=YouTube_Music -e 'Change header' -Ocustom=custom_branding_icon -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Custom header for YouTube Music' -e 'Disable music video in album' -e 'Return YouTube Username'"

[YouTube-Extended-dev]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
version = "auto"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomIcon=youtube -OcustomName=YouTube RVX -e 'Change header' -Ocustom=custom_branding_icon -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white"

[Music-Extended-dev]
enabled = false
app-name = "YouTube-Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
version = "auto"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomIcon=youtube_music -OcustomName=YouTube Music -e 'Change header' -Ocustom=custom_branding_icon -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white"

[Revanced]
enabled = false
app-name = "YouTube"
arch = "arm64-v8a"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Revanced-Music]
enabled = false
app-name = "YouTube-Music"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit]
enabled = false
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
version = "auto"

[Twitter-Dev]
enabled = true
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
patches-source = "crimera/piko"
rv-brand = "crimera"
arch = "arm64-v8a"
version = "auto"
patches-version = "dev"

[Twitter]
enabled = false
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
patches-source = "crimera/piko"
rv-brand = "crimera"
arch = "arm64-v8a"
version = "auto"
patches-version = "latest"

[Instagram]
enabled = false
arch = "arm64-v8a"
version = "auto"
included-patches = "'Hide ads' 'Limit feed to followed profiles' 'Anonymous story viewing' 'Hide suggested content' 'Enable developer menu' 'Sanitize sharing links'"
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Google-Photos]
enabled = false
arch = "arm64-v8a"
version = "auto"
included-patches = "'Enable DCIM folders backup control'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Proton-VPN]
enabled = false
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Icon-Pack-Studio]
enabled = false
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Messenger]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Twitch]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
