enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "both"
included-patches = "'Hide ads' 'Limit feed to followed profiles' 'Anonymous story viewing' 'Hide suggested content' 'Enable developer menu' 'Sanitize sharing links'"
exclusive-patches = true

[Messenger]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[YouTube_Music-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
build-mode = "both"
arch = "both"
version = "auto"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
build-mode = "both"
arch = "both"
version = "auto"

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Twitch]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
build-mode = "both"
arch = "both"
version = "auto"

[Youtube-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
build-mode = "both"
arch = "both"
version = "auto"

[Google_Photos]
build-mode = "both"
arch = "both"
version = "auto"
included-patches = "'Enable DCIM folders backup control'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Proton_VPN]
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"

[IconPackStudio]
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
